### ISSUE TITLE
Any plan on creating a new release

### ISSUE THREAD

**Issue by sabareeshkkanan** [pbernasconi/react-plaid-link#23]
I believe PR has already merged for fixing react 16 compatibility issue.

**Comment by pbernasconi** [comment]
@sabareeshkkanan definitely! I need to clean up 1 or two more things, and will create a new major release following that. Expect an update soon!

**Comment by TornikeNatsvlishvili** [comment]
@pbernasconi Any plans on the new release?

**Comment by Hani-RT** [comment]
@pbernasconi a new release would be fantastic.  I can't seem to use NPM to install with the latest commits, and I'm not too keen on forking the repo just to get the latest commits so that it's usable with my package.json.  When I try to install using `npm install --save pbernasconi/react-plaid-link#045b9b7`, I keep getting an error indicating that the react-plaid-link module is not found. Any alternative solutions you can suggest?

**Comment by TornikeNatsvlishvili** [comment]
@Hani-RT You're getting the error because master doesn't have a dist folder with the built JS.

You can instead use @cogell's fork: `npm install--save cogell/react-plaid-link#latest`

**Comment by pbernasconi** [comment]
Just release `v1.0.2` – sorry for the delay!

**Comment by Hani-RT** [comment]
@pbernasconi - thank you, thank you, thank you!!  :)

**Comment by bugrahanakcay** [comment]
Thank you...

On Mon, Jan 15, 2018 at 10:25 PM, Paolo Bernasconi <notifications@github.com
